name: Codacy Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Node dependencies
        working-directory: mi-vue-app
        run: |
          npm install

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v3  # Última versión disponible
        with:
          token: ${{ secrets.CODACY_PROJECT_TOKEN }}

