name: Codacy CLI Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verificar estructura de archivos (debug)
        run: ls -R

      - name: Install Node dependencies
        run: |
          cd mi-vue-app
          npm install

      - name: Download Codacy CLI
        run: |
          curl -L -o codacy-cli.jar https://github.com/codacy/codacy-analysis-cli/releases/latest/download/codacy-analysis-cli.jar

      - name: Run Codacy CLI Analysis
        run: |
          cd mi-vue-app
          java -jar ../codacy-cli.jar analyze \
            --tool eslint \
            --format json \
            --output ../codacy-results.json \
            || echo "::warning ::Análisis completado con advertencias."

      - name: Mostrar Resultados (en la consola de Actions)
        run: |
          echo "::group::Resultados de análisis"
          cat codacy-results.json
          echo "::endgroup::"

      - name: Marcar errores como anotaciones en GitHub (opcional)
        run: |
          node .github/scripts/codacy-to-annotations.js
        continue-on-error: true
